name: GitHub Pages

on:
  push:
    branches:
      - html # Cambia questo al branch che vuoi pubblicare, ad esempio main o html

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: actions/setup-ruby@v2  # Aggiorna la versione dell'azione
        with:
          ruby-version: '3.x'  # Verifica se vuoi una specifica versione di Ruby

      - name: Install dependencies
        run: bundle install
        
      - name: Build the site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
